name: Push Docker Image

on:
  push:

jobs:
  push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push to DockerHub
        uses: Mad-Pixels/github-workflows/.github/actions/dockerhub-build-push@main
        with:
          docker_user:  ${{ secrets.DOCKERHUB_USERNAME }}
          docker_token: ${{ secrets.DOCKERHUB_PASSWORD }}
          
          tag:        v1.7.7
          
          dockerfile_path: "./actionlint"
          repository: madpixels/actionlint
  
